#!/bin/bash

usage() {
  echo "usage:"
  echo "  $0 in [remote] [branch]"
  echo "  $0 out [remote]"
  exit 1
}

if [ $# -eq 0 ]; then
  usage
fi

method=$1

if [ -z $2 ]; then
  remote=origin
else
  remote=$2
fi

if [ -z $3 ]; then
  ref=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})
else
  ref=$remote/$3
fi

case $method in
  in)
    git ls-remote --exit-code ./. refs/remotes/$ref &>/dev/null
    if [ $? -eq 0 ]; then
      git log --pretty=format:'%C(auto)%h%d - %an, %ar: %s' --reverse HEAD..$ref
    else
      echo "Remote branch does not exist: $ref"
      exit 1
    fi
    ;;
  out)
    git log --pretty=format:'%C(auto)%h%d - %an, %ar: %s' --reverse --branches --not --remotes=$remote
    ;;
  *)
    usage
    ;;
esac
