#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ -z $1 ]]; then
  if [[ "$branch" == "master" ]]; then
    echo "usage: $0 [branch]"
    exit 1
  else
    git co master && git sync && git branch -d $branch

    if [[ $(git branch -a | grep -c remotes/origin/$branch) -eq 1 ]]; then
      git remote prune origin
    fi
  fi
else
  branch=$1
  if [[ "$branch" == "master" ]]; then
    echo "usage: $0 [branch]"
    exit 1
  fi
  git branch -d $branch && git push origin :$branch 2>/dev/null
fi
